### ISSUE TITLE
Sugestão: Criação de repositório para normas e conduta da comunida

### ISSUE THREAD

**Issue by Diego-Brocanelli** [PHPVale/phpvale.com.br#16]
Repositório destinado a esclarecer as normas e condutas que guiam a comunidade, para uma melhor condução e inclusão dos membros perante a sociedade.

**Comment by lucasxciv** [comment]
Acho que podemos nos basear em normas já escrito por outras comunidades.

**Comment by Diego-Brocanelli** [comment]
Sim, uma ótima referência é o do [Training Center](https://github.com/training-center/sobre/blob/master/CONDUCT.md).

**Comment by lucasxciv** [comment]
Repositório criado https://github.com/PHPVale/codigo-de-conduta

**Comment by Diego-Brocanelli** [comment]
Perfeito, irei trabalhar nele durante a semana.

**Comment by Diego-Brocanelli** [comment]
Boa noite,

Segue link do repositório para análise, caso positivo, vamos encerrar esta issue.

https://github.com/PHPVale/codigo-de-conduta

**Comment by Diego-Brocanelli** [comment]
Repositório criado [Código de Conduta para Colaboradores](https://github.com/PHPVale/codigo-de-conduta).
