### ISSUE TITLE
Sugestão: Criação do repositório Sobre

### ISSUE THREAD

**Issue by Diego-Brocanelli** [PHPVale/phpvale.com.br#17]
Repositório destinado a esclarecer e guiar a comunidade PHP Vale, deixando claro seus objetivos e metas.

**Comment by lucasxciv** [comment]
Objetivo já não seria incluído no repositório sugerido na issues #18?

**Comment by Diego-Brocanelli** [comment]
Inicialmente, pensei em conter somente o conteúdo de Missão, Visão e Valores e um outro repositório destinado a ser a central de informações do Grupo (Sobre).

**Comment by lucasxciv** [comment]
@Diego-Brocanelli você tem alguma ideia de como podemos criar esse repositório? Algum repositório de exemplo de alguma outra comunidade?

**Comment by Diego-Brocanelli** [comment]
Não me vem e mente algum exemplo, porém pensando melhor, a ideia dessa issue o próprio site já resolve, que é descrever nossos objetivos para a comunidade. Por mim eu fecharia essa issue.

**Comment by lucasxciv** [comment]
Blz! Por mim pode fechar também, caso tenha qualquer melhoria/alteração da descrição dos objetivos no site podemos reabrir essa issue ou criar uma nova.
