### ISSUE TITLE
Sugestão: Criação derepositório Jobs

### ISSUE THREAD

**Issue by Diego-Brocanelli** [PHPVale/phpvale.com.br#19]
Repositório destinado a listar vagas de empregos voltados a tecnologia PHP.

**Comment by lucasxciv** [comment]
Boa! Vamos usar as issues do Github, WP ou template que consome o JSON? @denilsonraimundo você que tem contribuído mais com o site o que acha?

**Comment by ghost** [comment]
Eu gosto da ideia de usar as issues do Github, é algo que muita gente usa e acredito que dê muito certo.

**Comment by lucasxciv** [comment]
Pessoal, o que acham de já criamos um fork desse repositório https://github.com/frontendbr/vagas para o PHPVale? Para já começarmos a organizar essa parte de vagas.

**Comment by heliomsolivas** [comment]
O padrão do frontendbr é bem maneiro, só direcionar pra vagas do vale mesmo.

**Comment by Diego-Brocanelli** [comment]
Bora reproduzir a ideia então?

**Comment by lucasxciv** [comment]
Repositório criado: https://github.com/PHPVale/vagas. O repositório do [phpdevbr](https://github.com/phpdevbr/vagas) é um fork dele também, podemos tirar algumas idéias.

**Comment by Diego-Brocanelli** [comment]
Maravilha @deoliveiralucas 

Abri uma PR realizando a adequação do fork  https://github.com/PHPVale/vagas/pull/1

**Comment by lucasxciv** [comment]
@Diego-Brocanelli Boa!

Fiz o *merge* e já subi algumas alterações https://github.com/PHPVale/vagas/pull/2

**Comment by Diego-Brocanelli** [comment]
PR aprovada :)

**Comment by Diego-Brocanelli** [comment]
Acredito que podemos fechar essa issue, o que acha?

**Comment by lucasxciv** [comment]
Por mim está ok, pode fachar.
