### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by 1fabiopereira** [PHPVale/phpvale.com.br#9]
Como posso ajudar ? :smile:

**Comment by Diego-Brocanelli** [comment]
Olá, @1fabiopereira 

Entre no nosso grupo do Telegram, para facilitar sua interação com a comunidade.

https://t.me/joinchat/CfuMTUbUybj7tLBH2FQ-MQ

**Comment by Diego-Brocanelli** [comment]
@1fabiopereira poderia encerrar essa issue?
